spring :
  datasource :
      password : 123456
      username : root
      url : jdbc:mysql://localhost:3306/daoli_office
      driverClassName: com.mysql.jdbc.Driver
      initialize : false
daoli:
  baseSavePath:
      "/apps/daoli"